# Generated by Django 5.2.8 on 2025-11-25 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_blogpost_author_remove_blogpost_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_provider', models.CharField(db_index=True, max_length=50)),
                ('exam_date', models.CharField(db_index=True, max_length=20)),
                ('daily_hours', models.PositiveIntegerField(default=8)),
                ('form_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'خطا')], db_index=True, default='draft', max_length=20)),
                ('generated_plan', models.JSONField(blank=True, null=True)),
                ('exam_code', models.CharField(blank=True, max_length=100, null=True)),
                ('target_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('period_days', models.PositiveIntegerField(default=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست برنامه\u200cریزی',
                'verbose_name_plural': 'درخواست\u200cهای برنامه\u200cریزی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_planner_user_id_88008b_idx'), models.Index(fields=['status', 'created_at'], name='api_planner_status_50831d_idx'), models.Index(fields=['expires_at'], name='api_planner_expires_a31911_idx')],
            },
        ),
    ]
