# Generated by Django 5.2.8 on 2025-11-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_plannerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('grade', models.IntegerField(db_index=True)),
                ('subject_category', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'ordering': ['grade', 'name'],
                'indexes': [models.Index(fields=['grade', 'subject_category'], name='api_book_grade_5ce264_idx')],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(db_index=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('exam_type', models.CharField(choices=[('Main', 'اصلی'), ('Base', 'پایه')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون\u200cها',
                'ordering': ['-exam_date'],
                'indexes': [models.Index(fields=['exam_date', 'exam_type'], name='api_exam_exam_da_e5e855_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyllabusDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=255)),
                ('pages', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_details', to='api.book')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_details', to='api.exam')),
            ],
            options={
                'verbose_name': 'جزئیات سرفصل',
                'verbose_name_plural': 'جزئیات سرفصل\u200cها',
                'ordering': ['exam', 'book', 'topic_title'],
                'indexes': [models.Index(fields=['exam', 'book'], name='api_syllabu_exam_id_1aa972_idx')],
            },
        ),
    ]
